### ISSUE TITLE
config option to set system-wide envelope-from address

### ISSUE THREAD

**Issue by surr** [bruceg/nullmailer#13]
My mail provider does not accept mail from non-existent addresses, but many system services are sending mail from non-existent generated adresses.

I suggest that envelope-from address may be forced to real admin address so mails could be delivered without troubles across the internet, and the real admin would receive bounces if any.

Internal From field may be leaved untouched.

**Comment by Organic-Marble** [comment]
This is awesome, and what I really needed on my system, instead of configuring every app. Thanks!!
