### ISSUE TITLE
Feature request: no option to specify SSL client key

### ISSUE THREAD

**Issue by jollyroger** [bruceg/nullmailer#14]
Hi, 

Thank you for your work! There has been long time since issue #3, but still there's no way to have certificate and private key located in a separate files. There is no a command-line option for this as well. From the source code (file: `protocols/tls_gnutls.cc`) I've found that nullmailer expects both certificate and private key to be in the same file:

```c
gnutls_wrap(gnutls_certificate_set_x509_key_file(creds, tls_x509certfile, tls_x509certfile, x509fmt)
```

However, it is a common approach to have separate files for certificate (that may be wold-readable) and private key (that should have a very limited access). In addition these files could be a part of PKI which means these files will be in different directories (for example, `/etc/ssl/certs` and `/etc/ssl/private`).

Thank you!

**Comment by bruceg** [comment]
Added support for separate keys in commit ed80ca125fbf418f6437fd166b921907cd3a70bf
