### ISSUE TITLE
Logging a successful delivery shouldn't be done at error-level

### ISSUE THREAD

**Issue by eolamey** [bruceg/nullmailer#21]
Hi,

Nullmailer logs every successful message delivery at error level, which is a bit confusing, and makes log analysis a bit harder.

Shouldn't this message be logged at a regular level?

It looks like the `fout` stream should be used instead of the `ferr` stream here https://github.com/bruceg/nullmailer/blob/master/protocols/protocol.cc#L76

Thank you.

**Comment by bruceg** [comment]
This probably is a leftover from an early design of the protocol modules, which had a separate agent (like tcpclient) opening up stdin/stdout as the socket.

Is there any reason both success and failure messages shouldn't be both logged to stdout?

**Comment by eolamey** [comment]
I don't mind it being logged on stdout, but a successful action being logged with a message of `Failed:` is at least a bit surprising :)

**Comment by bruceg** [comment]
There should never be a case of a successful action being logged with a message of `Failed:`, and simply changing `ferr` to `fout` would not affect that. Do you have examples of successful message deliveries being logged with `Failed:`?

**Comment by eolamey** [comment]
Sorry, I got it backwards, here's an exemple of a syslog message being indexed:

```javascript
{
  "message": "smtp: Succeeded: 250 2.0.0 Ok: queued as 3B664B0D",
  "type": "syslog",
  "syslog_program": "nullmailer",
  "syslog_facility": "mail",
  "syslog_severity": "error"
}
```

**Comment by bruceg** [comment]
nullmailer doesn't log messages to syslog. This is an issue with a patch to nullmailer, perhaps by Ubuntu.
