### ISSUE TITLE
Feature request: sender and receipient info in syslog

### ISSUE THREAD

**Issue by uffejakobsen** [bruceg/nullmailer#22]
Hi realizing that the nullmailer mailinglist is somewhat broken - the (web)archive does not work at least - so I'm reposting my feature request here

It would be nice if nullmailer logged sender and receipients info in syslog - the current logging is not of much use.

**Comment by hvenzke** [comment]
sutch critical data shuold NOT been logged by syslog.

**Comment by bruceg** [comment]
I started working on logging the envelope contents in nullmailer-send, but I'm not sure how best to do it. I'd like to make it a one-liner (From: <foo> to: <bar>) but that could make for rather long lines if there are multiple recipients.

**Comment by bruceg** [comment]
Implemented in b53e20452fba446b8fb81662b053e7256b20fada
