### ISSUE TITLE
nullmailer doesn't cope with spaces in arguments in "remotes"

### ISSUE THREAD

**Issue by nickleverton** [bruceg/nullmailer#23]
/etc/nullmailer/remotes:
mail.dom.invalid  smtp --user=somebody --pass="pass word" --starttls --insecure

results in this output from nullmailer-send:

Rescanning queue.
Starting delivery, 4 message(s) in queue.
Starting delivery: protocol: smtp host: mail.dom.invalid file: 1406854330.13523
smtp: Too many command-line arguments
usage: smtp [flags] remote-address < mail-file
... etc ...

The protocol helper is being called with an incorrect command line:

22:03:03.341912 execve("/usr/lib/nullmailer/smtp", ["/usr/lib/nullmailer/smtp", "--user=somebody", "--pass=\"pass", "
word\"", "--starttls", "--insecure", "mail.dom.invalid"], [/* 25 vars */]) = 0

Ubuntu bug 1318851
https://bugs.launchpad.net/ubuntu/+source/nullmailer/+bug/1318851

**Comment by bruceg** [comment]
Resolved by commit 74aeb537149c92eb4b8ba8173fc2d60eec086038
