### ISSUE TITLE
Read password from file instead of specifying in command line

### ISSUE THREAD

**Issue by yegle** [bruceg/nullmailer#24]
There should be a command line option `--pass-file` to . If when sending mail, the user specified `--pass-file`, the content in that file (excluding the newline char in the end) should be used as if `--pass` was specified using that value.

**Comment by bruceg** [comment]
I have a branch in progress that passes the options from the daemon to the protocols through a pipe rather than a file. This has the advantage of not requiring the protocol modules to open files, allowing them to be further secured against remote attacks.

**Comment by htgoebel** [comment]
Where can I find this branch? Has it already been merged?
