### ISSUE TITLE
nullmailer appending /etc/mailname to empty from addresses

### ISSUE THREAD

**Issue by borutmrak** [bruceg/nullmailer#27]
Hello,

I'm trying to use nullmailer on my mail storage VM (Dovecot) for sending messages from sieve (autoreplies, forwards etc.) out via central mail hub.

The problem I have is that nullmailer always appends contents of /etc/mailname so I get mail from: <@hostname.domain.tld> when the sender address is empty.

I'm using version 1.11 on Ubuntu 14.04, looking at the changelog I didn't see anything about this in 1.12 and 1.13 so I didn't try the latest version.

Is there a way to stop appending the mailname when from address is empty?

Thanks,
Borut Mrak.

P.S: I also checked the mailing list archive, but the archiver prints a python stack trace when clicking on a message, so the archive is not usable ATM :)

**Comment by bruceg** [comment]
There is no code present in nullmailer that references "/etc/mailname" in any form, nor does nullmailer modify empty sender addresses. I would have to think this is a custom Ubuntu patch. Have you asked on Ubuntu's bug tracker?
