### ISSUE TITLE
Nullmailer SMTP over TLS/SSL with cipher aNULL ?

### ISSUE THREAD

**Issue by uffejakobsen** [bruceg/nullmailer#33]
Hi,

Background:
The postfix mail server can be setup to use TLS (or STARTTLS) with no certificates either on server or client.
According to the postfix doc this should allow an smtp (MTA) client to connect and send encrypted emails without using certs.

I'm able to (sucessfully) test the connection to the server using the following openssl command:

openssl s_client -cipher aNULL -connect some.hostname.org:port

The above command enables me to manually go through the SMTP HELO etc dialog - works like a charm

Problem:
I cannot get nullmailer to deliver to the same server - I guess it is because I'm unable to specify the "-cipher aNULL" part in the remotes file.

Did I miss something here ?

Thanks in advance

**Comment by uffejakobsen** [comment]
I've created pull request (https://github.com/bruceg/nullmailer/pull/35) that adds TLS anonymous auth to nullmailer

**Comment by bruceg** [comment]
Resolved by fbdd0ba6613188ab375f6bdbb5747d18b583b90c
