### ISSUE TITLE
GCC compile error

### ISSUE THREAD

**Issue by zhuanyi** [bruceg/nullmailer#51]
Got the following error while trying to compile nullmailer-2.1:
```
sendmail.cc: In function 'int cli_main(int, char**)':
sendmail.cc:114:40: error: variable-sized object 'extra_args' may not be initialized
```
GCC version: gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by bruceg** [comment]
This doesn't even produce a warning for GCC 4.9, 5, or 6, so my immediate reaction is to upgrade to a newer compiler (GCC 4.7.2 is 5+ years old, and isn't even the latest bug fix in that series). AFAIK this is actually the right way of doing the initialization of a variable-length array, so I'm kinda surprised it doesn't work.

It'll take me a bit for me to get GCC 4.7.4 on my development box. In the mean time, you can probably work around this by dropping the `= {0}` part, and adding the following:
```
memset(extra_args, 0, (argc + 5) * sizeof *extra_args);
```

**Comment by zhuanyi** [comment]
My bad, the Debian on the server was not updated for too long, upgraded to Debian Jessie with GCC 4.9 and all is good.

**Comment by ckmaresca** [comment]
Just wanted to note I have the same issue on Ubuntu 14.04 - trying the work around, but am not a C coder...

**Comment by sibrat** [comment]
> Just wanted to note I have the same issue on Ubuntu 14.04 - trying the work around, but am not a C coder...

lines 114, 155 should look like this:

```
  const char* extra_args[argc + 5];
  memset(extra_args, 0, (argc + 5) * sizeof *extra_args);
```
